name: 'xero_source'
version: '0.4.1'
config-version: 2
require-dbt-version: [">=1.0.0", "<2.0.0"]

vars:
  xero_source:
    account: "{{ source('xero','account') }}"
    journal: "{{ source('xero','journal') }}"
    journal_line: "{{ source('xero','journal_line') }}"
    journal_line_has_tracking_category: "{{ source('xero','journal_line_has_tracking_category') }}"
    invoice: "{{ source('xero','invoice') }}"
    invoice_line_item: "{{ source('xero','invoice_line_item') }}"
    invoice_line_item_has_tracking_category: "{{ source('xero','invoice_line_item_has_tracking_category') }}"
    contact: "{{ source('xero','contact') }}"
    organization: "{{ source('xero','organization') }}"
    bank_transfer: "{{ source('xero','bank_transfer') }}"
    bank_transaction: "{{ source('xero','bank_transaction') }}"
    bank_transaction_line_item_has_tracking_category: "{{ source('xero','bank_transaction_line_item_has_tracking_category') }}"
    credit_note: "{{ source('xero','credit_note') }}"
    credit_note_line_item_has_tracking_category: "{{ source('xero','credit_note_line_item_has_tracking_category') }}"
    payment: "{{ source('xero','payment') }}"    
    overpayment: "{{ source('xero','overpayment') }}"
    overpayment_line_item: "{{ source('xero','overpayment_line_item') }}"
    overpayment_line_item_has_tracking_category: "{{ source('xero','overpayment_line_item_has_tracking_category') }}"
    manual_journal: "{{ source('xero','manual_journal') }}"
    manual_journal_line: "{{ source('xero','manual_journal_line') }}"
    manual_journal_line_has_tracking_category: "{{ source('xero','manual_journal_line_has_tracking_category') }}"
    
models:
  xero_source:
    +materialized: table
    +schema: stg_xero
    tmp:
      +materialized: view
